/* Convert GNV paths and materialize package-owned OpenVMS files.  */

#include <errno.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef PKGSRC_VMS_PATH_QUOTE_TEST
#include <descrip.h>
#include <fcntl.h>
#include <jpidef.h>
#include <lib$routines.h>
#include <lnmdef.h>
#include <rms.h>
#include <starlet.h>
#include <stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <unixlib.h>
#include <unixio.h>
#endif

#define COPY_BUFFER_SIZE 32768
#define RESULTANT_NAME_SIZE 4096
#define LOGICAL_VALUE_SIZE 256

#define EMACS22_STAGE_LOGICAL "EMACS22_STAGE"
#define EMACS22_IMAGE_NAME "EMACS-22_3.EXE"
#define EMACS22_DUMP_NAME "EMACS-22_3.DUMP"

#define DCL_COMMAND_LIMIT 1024
#define DCL_ELEMENT_LIMIT 255
#define DCL_ELEMENT_COUNT_LIMIT 127

static int
add_size (size_t *value, size_t addition)
{
  if (*value > (size_t) -1 - addition)
    {
      errno = EOVERFLOW;
      return 1;
    }
  *value += addition;
  return 0;
}

/* DCL preserves a double-quoted element and represents an embedded quote as
   two quotes.  Forced symbol substitution inside such an element requires
   two adjacent apostrophes, so reject that otherwise-unquotable sequence.  */
static int
dcl_quoted_length (const char *argument, size_t *result)
{
  const unsigned char *scan;
  size_t argument_length, quoted_length;
  int previous_apostrophe;

  argument_length = strlen (argument);
  if (argument_length > DCL_ELEMENT_LIMIT)
    {
      errno = E2BIG;
      return 1;
    }

  quoted_length = 2;
  previous_apostrophe = 0;
  for (scan = (const unsigned char *) argument; *scan != '\0'; scan++)
    {
      if (iscntrl (*scan))
        {
          errno = EINVAL;
          return 1;
        }
      if (*scan == '\'' && previous_apostrophe)
        {
          errno = EINVAL;
          return 1;
        }
      previous_apostrophe = *scan == '\'';
      if (add_size (&quoted_length, *scan == '"' ? 2 : 1) != 0)
        return 1;
    }
  *result = quoted_length;
  return 0;
}

static char *
append_dcl_quoted (char *target, const char *argument)
{
  const unsigned char *scan;

  *target++ = '"';
  for (scan = (const unsigned char *) argument; *scan != '\0'; scan++)
    {
      *target++ = (char) *scan;
      if (*scan == '"')
        *target++ = '"';
    }
  *target++ = '"';
  return target;
}

static int
ascii_alphanumeric (unsigned char character)
{
  return (character >= 'A' && character <= 'Z')
    || (character >= 'a' && character <= 'z')
    || (character >= '0' && character <= '9');
}

/* Accept only the physical native image specification generated by
   locate_emacs22.  This token cannot be double quoted for MCR, so reject
   logical devices, POSIX paths, malformed delimiters, and every file name
   except the package's fixed image name.  */
static int
native_emacs_image_path (const char *path, size_t path_length)
{
  const unsigned char *scan, *end, *device_name;

  scan = (const unsigned char *) path;
  end = scan + path_length;
  if (path_length == 0 || *scan++ != '_' || scan == end)
    return 0;
  device_name = scan;
  while (scan < end && *scan != ':')
    {
      if (!ascii_alphanumeric (*scan) && *scan != '$' && *scan != '_')
        return 0;
      scan++;
    }
  if (scan == device_name || scan == end || *scan++ != ':' || scan == end)
    return 0;

  do
    {
      unsigned char closing;
      int have_component_character;

      if (*scan == '[')
        closing = ']';
      else if (*scan == '<')
        closing = '>';
      else
        return 0;
      scan++;
      have_component_character = 0;
      while (scan < end && *scan != closing)
        {
          if (*scan < 32 || *scan == 127)
            return 0;
          if (*scan == '^')
            {
              scan++;
              if (scan == end || *scan < 32 || *scan == 127)
                return 0;
            }
          else if (*scan == '[' || *scan == ']' || *scan == '<'
                   || *scan == '>')
            return 0;
          have_component_character = 1;
          scan++;
        }
      if (!have_component_character || scan == end)
        return 0;
      scan++;
    }
  while (scan < end && (*scan == '[' || *scan == '<'));

  return (size_t) (end - scan) == sizeof EMACS22_IMAGE_NAME - 1
    && memcmp (scan, EMACS22_IMAGE_NAME, sizeof EMACS22_IMAGE_NAME - 1) == 0;
}

static int
dcl_file_character_safe (unsigned char character, int delimiter_depth,
                         int final_character)
{
  if (ascii_alphanumeric (character) || character >= 128)
    return 1;
  if (character == '$' || character == '_' || character == ':'
      || character == '[' || character == ']' || character == '<'
      || character == '>' || character == '.' || character == ';'
      || character == '*' || character == '%' || character == '?')
    return 1;
  if (character == '-' && !final_character)
    return 1;
  return character == ',' && delimiter_depth > 0;
}

/* Match vms-dcl-file-argument in vms-patch.el.  Complete native file specs
   must not be double quoted for MCR.  Preserve RMS caret escapes and add a
   caret before every otherwise-tokenized character.  */
static int
dcl_file_argument_length (const char *argument, size_t *result)
{
  const unsigned char *scan;
  size_t argument_length, escaped_length, carets, index;
  int delimiter_depth;

  argument_length = strlen (argument);
  if (argument_length > DCL_ELEMENT_LIMIT)
    {
      errno = E2BIG;
      return 1;
    }
  escaped_length = 0;
  carets = 0;
  delimiter_depth = 0;
  for (scan = (const unsigned char *) argument, index = 0;
       *scan != '\0'; scan++, index++)
    {
      if (*scan < 32 || *scan == 127)
        {
          errno = EINVAL;
          return 1;
        }
      if (*scan == '^')
        carets++;
      else
        {
          if ((carets & 1) == 0)
            {
              if (!dcl_file_character_safe
                    (*scan, delimiter_depth, index + 1 == argument_length)
                  && add_size (&escaped_length, 1) != 0)
                return 1;
              if (*scan == '[' || *scan == '<')
                delimiter_depth++;
              else if ((*scan == ']' || *scan == '>')
                       && delimiter_depth > 0)
                delimiter_depth--;
            }
          carets = 0;
        }
      if (add_size (&escaped_length, 1) != 0)
        return 1;
    }
  if ((carets & 1) != 0)
    {
      errno = EINVAL;
      return 1;
    }
  if (escaped_length > DCL_ELEMENT_LIMIT)
    {
      errno = E2BIG;
      return 1;
    }
  *result = escaped_length;
  return 0;
}

static char *
append_dcl_file_argument (char *target, const char *argument)
{
  const unsigned char *scan;
  size_t carets, index, argument_length;
  int delimiter_depth;

  argument_length = strlen (argument);
  carets = 0;
  delimiter_depth = 0;
  for (scan = (const unsigned char *) argument, index = 0;
       *scan != '\0'; scan++, index++)
    {
      if (*scan == '^')
        carets++;
      else
        {
          if ((carets & 1) == 0)
            {
              if (!dcl_file_character_safe
                    (*scan, delimiter_depth, index + 1 == argument_length))
                *target++ = '^';
              if (*scan == '[' || *scan == '<')
                delimiter_depth++;
              else if ((*scan == ']' || *scan == '>')
                       && delimiter_depth > 0)
                delimiter_depth--;
            }
          carets = 0;
        }
      *target++ = (char) *scan;
    }
  return target;
}

static int
build_dcl_mcr_command (const char *image_path, const char *dump_path,
                       int argument_count, char *const *arguments,
                       char **result)
{
  static const char map_option[] = "-map";
  const char *fixed_arguments[2];
  char *command, *target;
  size_t command_length, image_length, quoted_length;
  int i;

  if (argument_count < 0
      || argument_count > DCL_ELEMENT_COUNT_LIMIT - 3)
    {
      errno = E2BIG;
      return 1;
    }

  fixed_arguments[0] = map_option;
  fixed_arguments[1] = dump_path;
  command_length = sizeof "MCR" - 1;
  if (!native_emacs_image_path (image_path, strlen (image_path)))
    {
      errno = EINVAL;
      return 1;
    }
  if (dcl_file_argument_length (image_path, &image_length) != 0
      || add_size (&command_length, 1) != 0
      || add_size (&command_length, image_length) != 0)
    return 1;
  for (i = 0; i < 2; i++)
    {
      if (dcl_quoted_length (fixed_arguments[i], &quoted_length) != 0
          || add_size (&command_length, 1) != 0
          || add_size (&command_length, quoted_length) != 0)
        return 1;
    }
  for (i = 0; i < argument_count; i++)
    {
      if (dcl_quoted_length (arguments[i], &quoted_length) != 0
          || add_size (&command_length, 1) != 0
          || add_size (&command_length, quoted_length) != 0)
        return 1;
    }
  if (command_length > DCL_COMMAND_LIMIT)
    {
      errno = E2BIG;
      return 1;
    }
  if (add_size (&command_length, 1) != 0)
    return 1;
  command = (char *) malloc (command_length);
  if (!command)
    return 1;

  memcpy (command, "MCR", sizeof "MCR" - 1);
  target = command + sizeof "MCR" - 1;
  *target++ = ' ';
  target = append_dcl_file_argument (target, image_path);
  for (i = 0; i < 2; i++)
    {
      *target++ = ' ';
      target = append_dcl_quoted (target, fixed_arguments[i]);
    }
  for (i = 0; i < argument_count; i++)
    {
      *target++ = ' ';
      target = append_dcl_quoted (target, arguments[i]);
    }
  *target = '\0';
  *result = command;
  return 0;
}

/* NAML can expose a rooted physical path as [000000.][directory].  Such a
   pair of directory groups is useful as a parse result but is not a valid
   concealed-logical equivalence.  Select the second group for the prefix;
   callers that build exact image names continue to use the original text.  */
static void
prefix_directory_view (const char *directory, size_t directory_length,
                       const char **result, size_t *result_length)
{
  static const char square_root[] = "[000000.]";
  static const char angle_root[] = "<000000.>";
  size_t root_length;

  root_length = sizeof square_root - 1;
  if (directory_length > root_length
      && ((memcmp (directory, square_root, root_length) == 0
           && directory[root_length] == '[')
          || (memcmp (directory, angle_root, root_length) == 0
              && directory[root_length] == '<')))
    {
      directory += root_length;
      directory_length -= root_length;
    }
  *result = directory;
  *result_length = directory_length;
}

static int
ascii_bytes_equal (const char *left, size_t left_length,
                   const char *right, size_t right_length)
{
  size_t i;

  if (left_length != right_length)
    return 0;
  for (i = 0; i < left_length; i++)
    if (toupper ((unsigned char) left[i])
        != toupper ((unsigned char) right[i]))
      return 0;
  return 1;
}

/* NOCONCEAL can retain the physical-root group in an exact file name even
   though the package prefix must omit it to form a concealed logical.  Treat
   only that one documented representation difference as path equivalence.  */
static int
physical_paths_equal (const char *left, size_t left_length,
                      const char *right, size_t right_length)
{
  const char *left_colon, *right_colon;
  const char *left_directory, *right_directory;
  size_t left_device_length, right_device_length;
  size_t left_directory_length, right_directory_length;

  left_colon = (const char *) memchr (left, ':', left_length);
  right_colon = (const char *) memchr (right, ':', right_length);
  if (!left_colon || !right_colon)
    return ascii_bytes_equal (left, left_length, right, right_length);

  left_device_length = (size_t) (left_colon - left) + 1;
  right_device_length = (size_t) (right_colon - right) + 1;
  if (!ascii_bytes_equal (left, left_device_length,
                          right, right_device_length))
    return 0;

  prefix_directory_view (left + left_device_length,
                         left_length - left_device_length,
                         &left_directory, &left_directory_length);
  prefix_directory_view (right + right_device_length,
                         right_length - right_device_length,
                         &right_directory, &right_directory_length);
  return ascii_bytes_equal (left_directory, left_directory_length,
                            right_directory, right_directory_length);
}

static int
matches_versionless_path (const char *exact_path, const char *expected_path)
{
  const char *version;

  version = strrchr (exact_path, ';');
  return version
    && physical_paths_equal (exact_path, (size_t) (version - exact_path),
                             expected_path, strlen (expected_path));
}

#ifndef PKGSRC_VMS_PATH_QUOTE_TEST

/* RMS's SETRFM extension is intentionally not exposed by every OpenVMS
   header set even though SYS$MODIFY is available on the supported systems.  */
#ifndef RME$C_SETRFM
# define RME$C_SETRFM 1
#endif

static int output_count;

struct logical_item
{
  unsigned short buffer_length;
  unsigned short item_code;
  void *buffer_address;
  void *return_length_address;
};

static int
vms_failure (const char *operation, unsigned int status)
{
  errno = EVMSERR;
  vaxc$errno = status;
  perror (operation);
  return 1;
}

static int
escaped_character (const char *string, size_t position)
{
  size_t carets;

  carets = 0;
  while (position != 0 && string[position - 1] == '^')
    {
      carets++;
      position--;
    }
  return (carets & 1) != 0;
}

static int
ascii_name_equal (const char *string, size_t length, const char *name)
{
  return ascii_bytes_equal (string, length, name, strlen (name));
}

static int
append_bytes (char *destination, size_t destination_size, size_t *length,
              const char *source, size_t source_length)
{
  if (source_length >= destination_size
      || *length > destination_size - source_length - 1)
    {
      errno = ENAMETOOLONG;
      return 1;
    }
  memcpy (destination + *length, source, source_length);
  *length += source_length;
  destination[*length] = '\0';
  return 0;
}

static int
locate_emacs22 (char *image_path, size_t image_path_size,
                char *dump_path, size_t dump_path_size,
                char *root, size_t root_size,
                char *physical_prefix, size_t physical_prefix_size)
{
  char image_name[NAML$C_MAXRSS + 1];
  char expanded_name[NAML$C_MAXRSS + 1];
  char resultant_name[NAML$C_MAXRSS + 1];
  char device[NAML$C_MAXRSS + 1];
  char parent_directory[NAML$C_MAXRSS + 1];
  struct dsc$descriptor_s image_descriptor;
  struct FAB fab;
  struct NAML naml;
  char *directory;
  const char *prefix_directory;
  size_t device_length, directory_length, component_start;
  size_t separator, parent_length, prefix_directory_length;
  size_t prefix_length, root_length, path_length, i;
  unsigned short image_length;
  unsigned int status;
  int item;
  char closing_delimiter;

  item = JPI$_IMAGNAME;
  image_length = 0;
  image_descriptor.dsc$w_length = sizeof image_name - 1;
  image_descriptor.dsc$b_dtype = DSC$K_DTYPE_T;
  image_descriptor.dsc$b_class = DSC$K_CLASS_S;
  image_descriptor.dsc$a_pointer = image_name;
  status = lib$getjpi (&item, 0, 0, 0, &image_descriptor, &image_length);
  if (!(status & 1))
    return vms_failure ("emacs22-vms-path: current image", status);
  if (image_length == 0 || image_length >= sizeof image_name)
    {
      errno = ENAMETOOLONG;
      return 1;
    }
  image_name[image_length] = '\0';

  fab = cc$rms_fab;
  naml = cc$rms_naml;
  fab.fab$l_fna = (char *) -1;
  fab.fab$b_fns = 0;
  fab.fab$l_naml = &naml;
  naml.naml$l_long_filename = image_name;
  naml.naml$l_long_filename_size = image_length;
  naml.naml$l_long_expand = expanded_name;
  naml.naml$l_long_expand_alloc = NAML$C_MAXRSS;
  naml.naml$l_long_result = resultant_name;
  naml.naml$l_long_result_alloc = NAML$C_MAXRSS;
  naml.naml$v_no_short_output = 1;
  naml.naml$b_nop |= NAM$M_NOCONCEAL;

  status = sys$parse (&fab);
  if (!(status & 1))
    return vms_failure ("emacs22-vms-path: parse current image", status);
  status = sys$search (&fab);
  if (!(status & 1))
    return vms_failure ("emacs22-vms-path: search current image", status);
  if (naml.naml$l_long_result_size == 0
      || naml.naml$l_long_result_size > NAML$C_MAXRSS)
    {
      errno = ENAMETOOLONG;
      return 1;
    }
  resultant_name[naml.naml$l_long_result_size] = '\0';
  if (naml.naml$l_long_node_size != 0
      || !naml.naml$l_long_dev || naml.naml$l_long_dev_size == 0
      || !naml.naml$l_long_dir || naml.naml$l_long_dir_size < 3)
    {
      errno = EINVAL;
      return 1;
    }

  device_length = naml.naml$l_long_dev_size;
  if (device_length >= sizeof device
      || naml.naml$l_long_dev[device_length - 1] != ':')
    {
      errno = EINVAL;
      return 1;
    }
  path_length = 0;
  if (naml.naml$l_long_dev[0] != '_')
    {
      device[path_length++] = '_';
      device[path_length] = '\0';
    }
  if (append_bytes (device, sizeof device, &path_length,
                    naml.naml$l_long_dev, device_length) != 0)
    return 1;
  device_length = path_length;

  directory = naml.naml$l_long_dir;
  directory_length = naml.naml$l_long_dir_size;
  closing_delimiter = directory[directory_length - 1];
  if (!((directory[0] == '[' && closing_delimiter == ']')
        || (directory[0] == '<' && closing_delimiter == '>')))
    {
      errno = EINVAL;
      return 1;
    }

  separator = (size_t) -1;
  component_start = 1;
  for (i = 1; i + 1 < directory_length; i++)
    if (directory[i] == '.' && !escaped_character (directory, i))
      {
        separator = i;
        component_start = i + 1;
      }
  if (!ascii_name_equal (directory + component_start,
                         directory_length - component_start - 1, "BIN"))
    {
      fputs ("emacs22-vms-path: current image is not in the package bin directory\n",
             stderr);
      errno = EINVAL;
      return 1;
    }

  if (separator == (size_t) -1)
    {
      parent_directory[0] = directory[0];
      memcpy (parent_directory + 1, "000000", 6);
      parent_directory[7] = closing_delimiter;
      parent_directory[8] = '\0';
      parent_length = 8;
    }
  else
    {
      if (separator + 2 > sizeof parent_directory)
        {
          errno = ENAMETOOLONG;
          return 1;
        }
      memcpy (parent_directory, directory, separator);
      parent_directory[separator] = closing_delimiter;
      parent_directory[separator + 1] = '\0';
      parent_length = separator + 1;
    }

  prefix_directory_view (parent_directory, parent_length,
                         &prefix_directory, &prefix_directory_length);
  if (prefix_directory_length < 2)
    {
      errno = EINVAL;
      return 1;
    }

  prefix_length = 0;
  physical_prefix[0] = '\0';
  if (append_bytes (physical_prefix, physical_prefix_size, &prefix_length,
                    device, device_length) != 0
      || append_bytes (physical_prefix, physical_prefix_size, &prefix_length,
                       prefix_directory, prefix_directory_length) != 0)
    return 1;

  root_length = 0;
  root[0] = '\0';
  if (append_bytes (root, root_size, &root_length,
                    device, device_length) != 0
      || append_bytes (root, root_size, &root_length,
                       prefix_directory, prefix_directory_length - 1) != 0
      || append_bytes (root, root_size, &root_length, ".", 1) != 0
      || append_bytes (root, root_size, &root_length,
                       &closing_delimiter, 1) != 0)
    return 1;
  if (root_length > 255)
    {
      errno = ENAMETOOLONG;
      return 1;
    }

  path_length = 0;
  image_path[0] = '\0';
  if (append_bytes (image_path, image_path_size, &path_length,
                    device, device_length) != 0
      || append_bytes (image_path, image_path_size, &path_length,
                       directory, directory_length) != 0
      || append_bytes (image_path, image_path_size, &path_length,
                       EMACS22_IMAGE_NAME, sizeof EMACS22_IMAGE_NAME - 1) != 0)
    return 1;

  path_length = 0;
  dump_path[0] = '\0';
  if (append_bytes (dump_path, dump_path_size, &path_length,
                    device, device_length) != 0
      || append_bytes (dump_path, dump_path_size, &path_length,
                       directory, directory_length) != 0
      || append_bytes (dump_path, dump_path_size, &path_length,
                       EMACS22_DUMP_NAME, sizeof EMACS22_DUMP_NAME - 1) != 0)
    return 1;
  return 0;
}

static int
print_physical_prefix (void)
{
  char image_path[NAML$C_MAXRSS + 1];
  char dump_path[NAML$C_MAXRSS + 1];
  char root[LOGICAL_VALUE_SIZE];
  char physical_prefix[LOGICAL_VALUE_SIZE];

  if (locate_emacs22 (image_path, sizeof image_path,
                      dump_path, sizeof dump_path,
                      root, sizeof root,
                      physical_prefix, sizeof physical_prefix) != 0)
    {
      if (errno != EVMSERR)
        perror ("emacs22-vms-path: locate physical prefix");
      return 1;
    }
  if (puts (physical_prefix) == EOF || fflush (stdout) != 0)
    {
      perror ("emacs22-vms-path: physical prefix");
      return 1;
    }
  return 0;
}

static int
define_emacs22_root (char *root)
{
  static $DESCRIPTOR (logical_name, EMACS22_STAGE_LOGICAL);
  static $DESCRIPTOR (table_name, "LNM$PROCESS_TABLE");
  struct logical_item item_list[3];
  unsigned int translation_attributes;
  unsigned int status;
  size_t length;

  length = strlen (root);
  if (length == 0 || length > 255)
    {
      errno = ENAMETOOLONG;
      return 1;
    }
  translation_attributes = LNM$M_CONCEALED | LNM$M_TERMINAL;
  item_list[0].buffer_length = sizeof translation_attributes;
  item_list[0].item_code = LNM$_ATTRIBUTES;
  item_list[0].buffer_address = &translation_attributes;
  item_list[0].return_length_address = 0;
  item_list[1].buffer_length = (unsigned short) length;
  item_list[1].item_code = LNM$_STRING;
  item_list[1].buffer_address = root;
  item_list[1].return_length_address = 0;
  item_list[2].buffer_length = 0;
  item_list[2].item_code = 0;
  item_list[2].buffer_address = 0;
  item_list[2].return_length_address = 0;

  /* A user-mode process logical is deliberately used here.  The DCL process
     spawned by system, and the image it invokes, inherit unconfined process
     logicals.  The definition reaches Emacs without leaking into the process
     that invoked this launcher after the launcher exits.  */
  status = sys$crelnm (0, &table_name, &logical_name, 0, item_list);
  if (!(status & 1))
    return vms_failure ("emacs22-vms-path: define EMACS22_STAGE", status);
  return 0;
}

static int
launch_emacs22 (int argc, char **argv)
{
  char image_path[NAML$C_MAXRSS + 1];
  char dump_path[NAML$C_MAXRSS + 1];
  char root[LOGICAL_VALUE_SIZE];
  char physical_prefix[LOGICAL_VALUE_SIZE];
  char *command;
  int launch_status, saved_errno;

  if (locate_emacs22 (image_path, sizeof image_path,
                      dump_path, sizeof dump_path,
                      root, sizeof root,
                      physical_prefix, sizeof physical_prefix) != 0)
    {
      if (errno != EVMSERR)
        perror ("emacs22-vms-path: locate runtime");
      return EXIT_FAILURE;
    }
  if (access (image_path, X_OK) != 0)
    {
      perror ("emacs22-vms-path: executable");
      return EXIT_FAILURE;
    }
  if (access (dump_path, R_OK) != 0)
    {
      perror ("emacs22-vms-path: dump");
      return EXIT_FAILURE;
    }
  if (build_dcl_mcr_command (image_path, dump_path, argc - 2, argv + 2,
                             &command) != 0)
    {
      perror ("emacs22-vms-path: DCL command");
      return EXIT_FAILURE;
    }
  if (define_emacs22_root (root) != 0)
    {
      free (command);
      return EXIT_FAILURE;
    }

  /* execv shifts this legacy Emacs image's mapped sections on x86-64.  MCR
     uses the native image activation path used by RUNEMACS.COM.  Return the
     completion status unchanged so the GNV caller sees Emacs's status.  */
  launch_status = system (command);
  saved_errno = errno;
  free (command);
  if (launch_status != -1)
    return launch_status;
  errno = saved_errno;
  perror ("emacs22-vms-path: launch");
  return EXIT_FAILURE;
}

static int
replace_startup_marker (const char *path, const char *replacement)
{
  static const char marker[] = "__PKGSRC_EMACS22_PREFIX__";
  FILE *stream;
  char *input, *output, *source, *target, *match;
  long file_length;
  size_t bytes_read;
  size_t size, marker_length, replacement_length, count, output_size;

  stream = fopen (path, "rb", "ctx=stm");
  if (!stream)
    return 1;
  if (fseek (stream, 0, SEEK_END) != 0
      || (file_length = ftell (stream)) < 0
      || fseek (stream, 0, SEEK_SET) != 0)
    {
      fclose (stream);
      return 1;
    }
  size = (size_t) file_length;
  input = (char *) malloc (size + 1);
  if (!input)
    {
      fclose (stream);
      return 1;
    }
  bytes_read = fread (input, 1, size, stream);
  if (fclose (stream) != 0 || bytes_read != size)
    {
      free (input);
      return 1;
    }
  input[size] = '\0';

  marker_length = sizeof marker - 1;
  replacement_length = strlen (replacement);
  count = 0;
  for (source = input; (match = strstr (source, marker)) != 0;
       source = match + marker_length)
    count++;
  if (count == 0)
    {
      free (input);
      return 1;
    }
  if (replacement_length > marker_length)
    {
      size_t growth = replacement_length - marker_length;
      if (count > ((size_t) -1 - size) / growth)
        {
          free (input);
          return 1;
        }
      output_size = size + count * growth;
    }
  else
    output_size = size - count * (marker_length - replacement_length);
  if (output_size == (size_t) -1)
    {
      free (input);
      return 1;
    }
  output = (char *) malloc (output_size + 1);
  if (!output)
    {
      free (input);
      return 1;
    }

  source = input;
  target = output;
  while ((match = strstr (source, marker)) != 0)
    {
      size_t prefix_length = (size_t) (match - source);
      memcpy (target, source, prefix_length);
      target += prefix_length;
      memcpy (target, replacement, replacement_length);
      target += replacement_length;
      source = match + marker_length;
    }
  memcpy (target, source, (size_t) (input + size - source));
  output[output_size] = '\0';
  free (input);
  if (strstr (output, marker) != 0)
    {
      free (output);
      return 1;
    }

  /* The caller passes the exact version returned by getname.  Open it for
     update without O_CREAT or O_TRUNC so that replacing the marker cannot
     create, or accidentally select, another OpenVMS file version.  */
  stream = fopen (path, "r+b", "ctx=stm");
  if (!stream)
    {
      free (output);
      return 1;
    }
  if (fwrite (output, 1, output_size, stream) != output_size
      || fflush (stream) != 0
      || ftruncate (fileno (stream), (off_t) output_size) != 0
      || fsync (fileno (stream)) != 0)
    {
      fclose (stream);
      free (output);
      return 1;
    }
  if (fclose (stream) != 0)
    {
      free (output);
      return 1;
    }
  free (output);
  return 0;
}

static int
has_exact_version (const char *path)
{
  const char *version;
  int positive;

  version = strrchr (path, ';');
  if (!version || version[1] == '\0')
    return 0;
  version++;
  positive = 0;
  while (*version != '\0')
    {
      if (*version < '0' || *version > '9')
        return 0;
      if (*version != '0')
        positive = 1;
      version++;
    }
  return positive;
}

/* Resolve an existing exact version through RMS, bypassing concealed logical
   names.  Package metadata must retain a physical name: otherwise changing a
   logical after installation could redirect rollback or deinstallation to a
   different file.  */
static int
canonicalize_exact_file (const char *path, char *result, size_t result_size)
{
  char expanded_name[NAML$C_MAXRSS + 1];
  struct FAB fab;
  struct NAML naml;
  size_t path_length;
  unsigned int status;

  if (!has_exact_version (path))
    {
      errno = EINVAL;
      return 1;
    }
  path_length = strlen (path);
  if (path_length > NAML$C_MAXRSS || result_size < 2)
    {
      errno = ENAMETOOLONG;
      return 1;
    }

  fab = cc$rms_fab;
  naml = cc$rms_naml;
  fab.fab$l_fna = (char *) -1;
  fab.fab$b_fns = 0;
  fab.fab$l_naml = &naml;
  naml.naml$l_long_filename = (char *) path;
  naml.naml$l_long_filename_size = path_length;
  naml.naml$l_long_expand = expanded_name;
  naml.naml$l_long_expand_alloc = NAML$C_MAXRSS;
  naml.naml$l_long_result = result;
  naml.naml$l_long_result_alloc = result_size - 1;
  naml.naml$v_no_short_output = 1;
  naml.naml$b_nop |= NAM$M_NOCONCEAL;

  status = sys$parse (&fab);
  if (status & 1)
    status = sys$search (&fab);
  if (!(status & 1))
    {
      errno = EVMSERR;
      vaxc$errno = status;
      return 1;
    }
  if (naml.naml$l_long_result_size == 0
      || naml.naml$l_long_result_size >= result_size)
    {
      errno = ENAMETOOLONG;
      return 1;
    }
  if (naml.naml$l_long_node_size != 0
      || !naml.naml$l_long_dev || naml.naml$l_long_dev != result
      || naml.naml$l_long_dev_size == 0
      || naml.naml$l_long_dev[naml.naml$l_long_dev_size - 1] != ':')
    {
      errno = EINVAL;
      return 1;
    }
  if (result[0] != '_')
    {
      if (naml.naml$l_long_result_size + 1 >= result_size)
        {
          errno = ENAMETOOLONG;
          return 1;
        }
      memmove (result + 1, result, naml.naml$l_long_result_size);
      result[0] = '_';
      naml.naml$l_long_result_size++;
    }
  result[naml.naml$l_long_result_size] = '\0';
  if (!has_exact_version (result))
    {
      errno = EIO;
      return 1;
    }
  return 0;
}

/* Change the exact dump version from the UDF format used while staging to
   the variable-record format expected by the OpenVMS Emacs map loader.  RMS
   returns the existing RFM and RAT from SYS$OPEN, so set both fields only
   after the open and before the RMS SETRFM extension's SYS$MODIFY call.  */
static int
set_dump_attributes (const char *path)
{
  struct FAB fab;
  struct NAML naml;
  size_t path_length;
  unsigned int status, modify_status, close_status;

  if (!has_exact_version (path))
    {
      errno = EINVAL;
      return 1;
    }
  path_length = strlen (path);
  if (path_length > NAML$C_MAXRSS)
    {
      errno = ENAMETOOLONG;
      return 1;
    }

  fab = cc$rms_fab;
  naml = cc$rms_naml;
  fab.fab$l_fna = (char *) -1;
  fab.fab$b_fns = 0;
  fab.fab$l_naml = &naml;
  fab.fab$b_fac = FAB$M_PUT;
  fab.fab$l_fop = FAB$M_ESC;
  fab.fab$l_ctx = RME$C_SETRFM;
  naml.naml$l_long_filename = (char *) path;
  naml.naml$l_long_filename_size = path_length;
  naml.naml$v_no_short_output = 1;

  status = sys$open (&fab);
  if (!(status & 1))
    return vms_failure ("emacs22-vms-path: open dump attributes", status);

  fab.fab$b_rfm = FAB$C_VAR;
  fab.fab$b_rat = 0;
  modify_status = sys$modify (&fab);
  close_status = sys$close (&fab);
  if (!(modify_status & 1))
    return vms_failure ("emacs22-vms-path: set dump attributes",
                        modify_status);
  if (!(close_status & 1))
    return vms_failure ("emacs22-vms-path: close dump attributes",
                        close_status);
  return 0;
}

static int
write_all (int descriptor, char *buffer, size_t length)
{
  size_t offset;

  offset = 0;
  while (offset < length)
    {
      int written;

      written = write (descriptor, buffer + offset, length - offset);
      if (written < 0)
        {
          if (errno == EINTR)
            continue;
          return 1;
        }
      if (written == 0)
        {
          errno = EIO;
          return 1;
        }
      offset += (size_t) written;
    }
  return 0;
}

/* Copy SOURCE to a newly created DESTINATION.  O_EXCL makes the test and
   creation one operation, and getname captures the exact OpenVMS version
   that this invocation owns.  Print that name only after the copy closes
   successfully; on every later failure remove only that exact version.  */
static int
copy_exclusive (const char *format, const char *source,
                const char *destination)
{
  char buffer[COPY_BUFFER_SIZE];
  char resultant[RESULTANT_NAME_SIZE];
  char physical_resultant[RESULTANT_NAME_SIZE];
  struct stat source_status;
  mode_t source_mode;
  int source_descriptor, destination_descriptor;
  int created, have_resultant, status, saved_errno;

  source_descriptor = -1;
  destination_descriptor = -1;
  created = 0;
  have_resultant = 0;
  status = 1;

  source_descriptor = open (source, O_RDONLY, 0, "ctx=stm");
  if (source_descriptor < 0)
    goto done;
  if (fstat (source_descriptor, &source_status) != 0)
    goto done;
  source_mode = source_status.st_mode & 0777;
  if (strcmp (format, "udf") == 0)
    destination_descriptor = open (destination,
                                   O_WRONLY | O_CREAT | O_EXCL, source_mode,
                                   "rfm=udf", "rat=none", "ctx=stm");
  else if (strcmp (format, "stmlf") == 0)
    destination_descriptor = open (destination,
                                   O_WRONLY | O_CREAT | O_EXCL, source_mode,
                                   "rfm=stmlf", "rat=none", "ctx=stm");
  else
    {
      errno = EINVAL;
      goto done;
    }
  if (destination_descriptor < 0)
    goto done;
  created = 1;
  if (!getname (destination_descriptor, resultant, 1)
      || !has_exact_version (resultant))
    {
      errno = EIO;
      goto done;
    }
  /* The exact versioned name returned by getname is already sufficient for
     failure cleanup.  Record ownership before physical canonicalization so
     that a later NAML failure cannot orphan the file just created above.  */
  have_resultant = 1;
  if (canonicalize_exact_file (resultant, physical_resultant,
                               sizeof physical_resultant) != 0)
    goto done;
  memcpy (resultant, physical_resultant, strlen (physical_resultant) + 1);

  for (;;)
    {
      int bytes_read;

      bytes_read = read (source_descriptor, buffer, sizeof buffer);
      if (bytes_read < 0)
        {
          if (errno == EINTR)
            continue;
          goto done;
        }
      if (bytes_read == 0)
        break;
      if (write_all (destination_descriptor, buffer,
                     (size_t) bytes_read) != 0)
        goto done;
    }

  if (close (source_descriptor) != 0)
    {
      source_descriptor = -1;
      goto done;
    }
  source_descriptor = -1;
  /* open applies the process umask; restore the packaged sidecar's mode on
     the descriptor for the exact version before publishing its name.  */
  if (fchmod (destination_descriptor, source_mode) != 0)
    goto done;
  if (fsync (destination_descriptor) != 0)
    goto done;
  if (close (destination_descriptor) != 0)
    {
      destination_descriptor = -1;
      goto done;
    }
  destination_descriptor = -1;
  if (puts (resultant) == EOF || fflush (stdout) != 0)
    goto done;
  status = 0;

 done:
  saved_errno = errno;
  if (source_descriptor >= 0)
    (void) close (source_descriptor);
  if (destination_descriptor >= 0)
    (void) close (destination_descriptor);
  if (status != 0 && created && have_resultant)
    (void) remove (resultant);
  errno = saved_errno;
  return status;
}

static int
build_child_path (const char *physical_prefix, const char *directory_name,
                  const char *file_name, char *path, size_t path_size)
{
  const char *opening;
  size_t prefix_length, directory_length, path_length;
  char closing;

  prefix_length = strlen (physical_prefix);
  if (prefix_length < 3)
    {
      errno = EINVAL;
      return 1;
    }
  closing = physical_prefix[prefix_length - 1];
  opening = strrchr (physical_prefix, closing == ']' ? '[' : '<');
  if (!opening || !((opening[0] == '[' && closing == ']')
                    || (opening[0] == '<' && closing == '>')))
    {
      errno = EINVAL;
      return 1;
    }
  directory_length = prefix_length - (size_t) (opening - physical_prefix) - 2;

  path[0] = '\0';
  path_length = 0;
  if (ascii_name_equal (opening + 1, directory_length, "000000"))
    {
      if (append_bytes (path, path_size, &path_length, physical_prefix,
                        (size_t) (opening - physical_prefix) + 1) != 0)
        return 1;
    }
  else
    {
      if (append_bytes (path, path_size, &path_length, physical_prefix,
                        prefix_length - 1) != 0
          || append_bytes (path, path_size, &path_length, ".", 1) != 0)
        return 1;
    }
  if (append_bytes (path, path_size, &path_length,
                    directory_name, strlen (directory_name)) != 0
      || append_bytes (path, path_size, &path_length, &closing, 1) != 0
      || append_bytes (path, path_size, &path_length,
                       file_name, strlen (file_name)) != 0)
    return 1;
  return 0;
}

static int
generated_file_in_self_prefix (const char *exact_path)
{
  char image_path[NAML$C_MAXRSS + 1];
  char dump_path[NAML$C_MAXRSS + 1];
  char startup_path[NAML$C_MAXRSS + 1];
  char root[LOGICAL_VALUE_SIZE];
  char physical_prefix[LOGICAL_VALUE_SIZE];

  if (locate_emacs22 (image_path, sizeof image_path,
                      dump_path, sizeof dump_path,
                      root, sizeof root,
                      physical_prefix, sizeof physical_prefix) != 0)
    return 0;
  if (build_child_path (physical_prefix, "STARTUP",
                        "EMACS-22_3_STARTUP.COM",
                        startup_path, sizeof startup_path) != 0)
    return 0;
  return matches_versionless_path (exact_path, dump_path)
    || matches_versionless_path (exact_path, startup_path);
}

static int
delete_exact (const char *path)
{
  char physical_path[RESULTANT_NAME_SIZE];

  if (!has_exact_version (path))
    {
      errno = EINVAL;
      return 1;
    }
  if (access (path, F_OK) != 0)
    return errno == ENOENT ? 0 : 1;
  if (canonicalize_exact_file (path, physical_path,
                               sizeof physical_path) != 0)
    return 1;
  if (!generated_file_in_self_prefix (physical_path))
    {
      errno = EPERM;
      return 1;
    }
  if (remove (physical_path) == 0 || errno == ENOENT)
    return 0;
  return 1;
}

static int
print_vms_path (char *path, int type)
{
  (void) type;
  if (output_count != 0)
    return 0;
  if (fputs (path, stdout) == EOF)
    return 0;
  output_count++;
  return 1;
}

int
main (int argc, char **argv)
{
  int converted;

  if (argc >= 2 && strcmp (argv[1], "--launch") == 0)
    return launch_emacs22 (argc, argv);

  if (argc == 2 && strcmp (argv[1], "--physical-prefix") == 0)
    return print_physical_prefix () == 0 ? EXIT_SUCCESS : EXIT_FAILURE;

  if (argc == 5 && strcmp (argv[1], "--copy-excl") == 0)
    {
      if (copy_exclusive (argv[2], argv[3], argv[4]) != 0)
        {
          perror ("emacs22-vms-path: exclusive copy");
          return EXIT_FAILURE;
        }
      return 0;
    }

  if (argc == 3 && strcmp (argv[1], "--delete-exact") == 0)
    {
      if (delete_exact (argv[2]) != 0)
        {
          perror ("emacs22-vms-path: exact delete");
          return EXIT_FAILURE;
        }
      return 0;
    }

  if (argc == 3 && strcmp (argv[1], "--set-dump-attrs") == 0)
    {
      if (set_dump_attributes (argv[2]) != 0)
        {
          if (errno != EVMSERR)
            perror ("emacs22-vms-path: dump attributes");
          return EXIT_FAILURE;
        }
      return 0;
    }

  if (argc == 4 && strcmp (argv[1], "--replace-startup-marker") == 0)
    return replace_startup_marker (argv[2], argv[3]) == 0
      ? EXIT_SUCCESS : EXIT_FAILURE;

  if (argc != 2 || argv[1][0] == '\0')
    {
      fputs ("usage: emacs22-vms-path unix-directory\n"
             "       emacs22-vms-path --copy-excl {udf|stmlf} source destination\n"
             "       emacs22-vms-path --delete-exact vms-file-version\n"
             "       emacs22-vms-path --launch [emacs-arguments ...]\n"
             "       emacs22-vms-path --physical-prefix\n"
             "       emacs22-vms-path --replace-startup-marker file prefix\n"
             "       emacs22-vms-path --set-dump-attrs vms-file-version\n",
             stderr);
      return 2;
    }

  /* Do not expand wildcards, and force directory interpretation even if the
     destination does not exist yet.  */
  converted = decc$to_vms (argv[1], print_vms_path, 0, 2);
  if (converted != 1 || output_count != 1 || ferror (stdout))
    return EXIT_FAILURE;
  return EXIT_SUCCESS;
}

#else /* PKGSRC_VMS_PATH_QUOTE_TEST */

static int
test_directory_view (const char *input, const char *expected)
{
  const char *view;
  size_t view_length;

  prefix_directory_view (input, strlen (input), &view, &view_length);
  return strlen (expected) == view_length
    && memcmp (view, expected, view_length) == 0;
}

int
main (void)
{
  static const char test_image[] =
    "_X86923$DKA200:[000000.][ECBROWN.pkg-clean.bin]EMACS-22_3.EXE";
  static char long_image[DCL_ELEMENT_LIMIT + 64];
  static char long_argument[DCL_ELEMENT_LIMIT + 2];
  static char *many_arguments[DCL_ELEMENT_COUNT_LIMIT];
  static char *arguments[] = {
    "plain", "two words", "a\"b", "O'Brien", "",
    "_D:[A]FILE.EL", "/tmp/file.el"
  };
  static const char expected[] =
    "MCR _X86923$DKA200:[000000.][ECBROWN.pkg-clean.bin]EMACS-22_3.EXE"
    " \"-map\" \"DEV:[D]IMAGE.DUMP\""
    " \"plain\" \"two words\" \"a\"\"b\" \"O'Brien\" \"\""
    " \"_D:[A]FILE.EL\" \"/tmp/file.el\"";
  char *command;
  int i;

  if (build_dcl_mcr_command (test_image, "DEV:[D]IMAGE.DUMP",
                             sizeof arguments / sizeof arguments[0],
                             arguments, &command) != 0)
    return 1;
  if (strcmp (command, expected) != 0)
    {
      fprintf (stderr, "unexpected command: %s\n", command);
      free (command);
      return 1;
    }
  free (command);

  if (build_dcl_mcr_command
        ("_D:[A B!C^ D'Q&X|Y\"Z]EMACS-22_3.EXE", "D", 0, arguments,
         &command) != 0)
    return 1;
  if (strcmp (command,
              "MCR _D:[A^ B^!C^ D^'Q^&X^|Y^\"Z]EMACS-22_3.EXE"
              " \"-map\" \"D\"") != 0)
    {
      fprintf (stderr, "unexpected escaped image: %s\n", command);
      free (command);
      return 1;
    }
  free (command);

  errno = 0;
  if (build_dcl_mcr_command ("DEV:[D]EMACS-22_3.EXE", "D", 0,
                             arguments, &command) == 0
      || errno != EINVAL)
    return 1;
  errno = 0;
  if (build_dcl_mcr_command ("_D:[BAD^]EMACS-22_3.EXE", "D", 0,
                             arguments, &command) == 0
      || errno != EINVAL)
    return 1;
  errno = 0;
  if (build_dcl_mcr_command ("_D:[BAD\nDIR]EMACS-22_3.EXE", "D", 0,
                             arguments, &command) == 0
      || errno != EINVAL)
    return 1;
  memcpy (long_image, "_D:[", sizeof "_D:[" - 1);
  memset (long_image + sizeof "_D:[" - 1, 'A', DCL_ELEMENT_LIMIT);
  memcpy (long_image + sizeof "_D:[" - 1 + DCL_ELEMENT_LIMIT,
          "]" EMACS22_IMAGE_NAME, sizeof "]" EMACS22_IMAGE_NAME);
  errno = 0;
  if (build_dcl_mcr_command (long_image, "D", 0, arguments, &command) == 0
      || errno != E2BIG)
    return 1;

  errno = 0;
  arguments[0] = "line\nbreak";
  if (build_dcl_mcr_command (test_image, "D", 1, arguments, &command) == 0
      || errno != EINVAL)
    return 1;
  errno = 0;
  arguments[0] = "unsafe''symbol'";
  if (build_dcl_mcr_command (test_image, "D", 1, arguments, &command) == 0
      || errno != EINVAL)
    return 1;

  memset (long_argument, 'x', sizeof long_argument - 1);
  long_argument[sizeof long_argument - 1] = '\0';
  arguments[0] = long_argument;
  errno = 0;
  if (build_dcl_mcr_command (test_image, "D", 1, arguments, &command) == 0
      || errno != E2BIG)
    return 1;

  long_argument[250] = '\0';
  for (i = 0; i < 5; i++)
    arguments[i] = long_argument;
  errno = 0;
  if (build_dcl_mcr_command (test_image, "D", 5, arguments, &command) == 0
      || errno != E2BIG)
    return 1;

  for (i = 0; i < DCL_ELEMENT_COUNT_LIMIT; i++)
    many_arguments[i] = "x";
  errno = 0;
  if (build_dcl_mcr_command (test_image, "D",
                             DCL_ELEMENT_COUNT_LIMIT - 2,
                             many_arguments, &command) == 0
      || errno != E2BIG)
    return 1;

  if (!test_directory_view ("[000000.][A.B]", "[A.B]")
      || !test_directory_view ("<000000.><A.B>", "<A.B>")
      || !test_directory_view ("[A.B]", "[A.B]"))
    return 1;

  /* Model the ownership comparison performed after --delete-exact
     canonicalizes a generated startup file with NOCONCEAL.  */
  if (!matches_versionless_path
        ("_D:[000000.][PKG.STARTUP]EMACS-22_3_STARTUP.COM;17",
         "_D:[PKG.STARTUP]EMACS-22_3_STARTUP.COM")
      || !matches_versionless_path
           ("_D:<000000.><PKG.STARTUP>EMACS-22_3_STARTUP.COM;17",
            "_D:<PKG.STARTUP>EMACS-22_3_STARTUP.COM")
      || !matches_versionless_path
           ("_D:[PKG.BIN]EMACS-22_3.DUMP;2",
            "_D:[PKG.BIN]EMACS-22_3.DUMP")
      || matches_versionless_path
           ("_D:[000000.][OTHER.STARTUP]EMACS-22_3_STARTUP.COM;17",
            "_D:[PKG.STARTUP]EMACS-22_3_STARTUP.COM")
      || matches_versionless_path
           ("_D:[000000.][PKG.STARTUP]EMACS-22_3_STARTUP.COM",
            "_D:[PKG.STARTUP]EMACS-22_3_STARTUP.COM"))
    return 1;

  puts ("pkgsrc_vms_path quoting tests passed");
  return 0;
}

#endif /* PKGSRC_VMS_PATH_QUOTE_TEST */
