# $NetBSD: Makefile.common,v 1.172 2026/04/06 21:38:35 morr Exp $
# used by editors/vim/Makefile
# used by editors/vim-gtk2/Makefile
# used by editors/vim-gtk3/Makefile
# used by editors/vim-lang/Makefile
# used by editors/vim-motif/Makefile

.include "../../editors/vim-share/version.mk"

DISTNAME=		vim-${VIM_VERSION}.${VIM_PATCHLEVEL}
CATEGORIES=		editors
GITHUB_PROJECT=		vim
GITHUB_TAG=		v${VIM_VERSION}.${VIM_PATCHLEVEL}
MASTER_SITES=		${MASTER_SITE_GITHUB:=vim/}

# vim disables it, sometimes unsuccessfully.
FORTIFY_SUPPORTED=	no

.include "../../mk/bsd.prefs.mk"

.if ${OPSYS} == "OpenVMS"
NO_CONFIGURE=		yes

# Vim has a native OpenVMS MMS build.  Compile the pkgsrc installation paths
# into the image so it can find its runtime files without login-specific
# VIM and VIMRUNTIME logical names.
SUBST_CLASSES+=		vms-paths
SUBST_STAGE.vms-paths=	pre-build
SUBST_FILES.vms-paths=	Make_vms.mms
SUBST_VARS.vms-paths=	PREFIX VIM_SUBDIR
.else
GNU_CONFIGURE=		yes
.endif

MAINTAINER=		morr@NetBSD.org
HOMEPAGE=		https://www.vim.org/
LICENSE=		vim-license OR gnu-gpl-v2

WRKSRC=			${WRKDIR}/${DISTNAME}/src
USE_LANGUAGES+=		c

# http://www.netbsd.org/cgi-bin/query-pr-single.pl?number=38710
CHECK_INTERPRETER_SKIP=	share/vim/${VIM_SUBDIR}/tools/vim132

.include "options.mk"

CONFIGURE_ARGS+=	--with-modified-by=${MAINTAINER:Q}

# See "configure --help" extra options. These might affect the installed
# files (and PLIST might not include all files) so use at your own risk!
CONFIGURE_ARGS+=	${VIM_EXTRA_OPTS}
CONFIGURE_ARGS+=	--enable-multibyte
CONFIGURE_ARGS+=	--enable-cscope

PATCH_ARGS=		-d ${WRKDIR}/${DISTNAME} --forward --quiet \
				-E ${PATCH_STRIP:Q}
PATCH_DIST_ARGS=	-d ${WRKDIR}/${DISTNAME} --forward --quiet \
				-E ${PATCH_DIST_STRIP:Q}
PATCHDIR=		${.CURDIR}/../../editors/vim-share/patches
DISTINFO_FILE?=		${.CURDIR}/../../editors/vim-share/distinfo

.if ${OPSYS} == "Darwin" && exists(/Developer/Headers/FlatCarbon)
BUILDLINK_PASSTHRU_DIRS+=	/Developer/Headers/FlatCarbon
.endif

# Haiku needs -lgnu for the xattr family of functions.
# Haikuports also adds -lgnu but doesn't explain why.
LIBS.Haiku+=		-lgnu
LIBS.SunOS+=		-lnsl

.if empty(PKGNAME:Mvim-share*)
ALTERNATIVES_SRC=	${.CURDIR}/../../editors/vim-share/ALTERNATIVES
.else
ALTERNATIVES_SRC=
.endif

SUBST_CLASSES+=		sysconfdir
SUBST_FILES.sysconfdir=	feature.h
.if ${OPSYS} == "OpenVMS"
SUBST_STAGE.sysconfdir=	pre-build
.else
SUBST_STAGE.sysconfdir=	pre-configure
.endif
SUBST_VARS.sysconfdir=	PKG_SYSCONFDIR

post-patch:
	find ${WRKDIR} -name '*.orig_dist' -exec rm -f {} \;
