#! /bin/sh
# mkinstalldirs --- make directory hierarchy
# Author: Noah Friedman <friedman@prep.ai.mit.edu>
# Created: 1993-05-16
# Public domain

# $Id: mkinstalldirs,v 1.1 2002/12/21 04:06:15 schmonz Exp $

errstatus=0

openvms=no
case `uname -s 2>/dev/null` in
OpenVMS) openvms=yes ;;
esac

for file
do
   set fnord `echo ":$file" | sed -ne 's/^:\//#/;s/^://;s/\// /g;s/^#/\//;p'`
   shift

   pathcomp=
   for d
   do
     pathcomp="$pathcomp$d"
     case "$pathcomp" in
       -* ) pathcomp=./$pathcomp ;;
     esac

     # GNV's test(1) does not recognize a bare OpenVMS volume root such as
     # /PKGSRC_DATA as a directory, while mkdir correctly reports that it
     # already exists.  A volume root cannot be created here, so leave it for
     # the following path components.
     if test "$openvms" = yes; then
       case "$pathcomp" in
         /*)
           case "${pathcomp#/}" in
             */*) ;;
             *) pathcomp="$pathcomp/"; continue ;;
           esac ;;
       esac
     fi

     if test ! -d "$pathcomp"; then
        echo "mkdir $pathcomp"

        mkdir "$pathcomp" || lasterr=$?

        if test ! -d "$pathcomp"; then
  	  errstatus=$lasterr
        fi
     fi

     pathcomp="$pathcomp/"
   done
done

exit $errstatus

# mkinstalldirs ends here
